import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Sidebar from "@/components/Sidebar";
import PersonalInfo from "@/components/PersonalInfo";
import SelectPlans from "@/components/SelectPlans";
import { useState } from "react";
import AddOns from "@/components/AddOns";
import Summary from "@/components/Summary";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  const [activeIndex, setActiveIndex] = useState(0);

  return (
    <>
      <Head>
        <title>Personal info form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.home}>
        <div className={styles.home_container}>
          <Sidebar activeForm={activeIndex} />
          
          {activeIndex === 0 ? <PersonalInfo
            isActive={activeIndex === 0}
            onShow={() => {
              setActiveIndex(1);
            }}
          /> : ""}

          {activeIndex === 1 ? <SelectPlans
            onShow={() => {
              setActiveIndex(2);
            }}
          /> : ""}

          {activeIndex === 2 ? <AddOns
            onShow={() => {
              setActiveIndex(3);
            }}
          /> : ""}

          {activeIndex === 3 ? <Summary
            onShow={() => {
              setActiveIndex(0);
            }}
          /> : ""}

        </div>
      </section>
    </>
  );
}
