import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Sidebar from "@/components/Sidebar";
import PersonalInfo from "@/components/PersonalInfo";
import SelectPlans from "@/components/SelectPlans";
import { useState } from "react";
import AddOns from "@/components/AddOns";
import Summary from "@/components/Summary";

export default function Home() {
  const [activeIndex, setActiveIndex] = useState(0);

  return (
    <>
      <Head>
        <title>Personal info form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className={styles.home}>
        <div className={styles.home_container}>
          <Sidebar activeIndex={activeIndex} setActiveIndex={setActiveIndex} />

          {activeIndex === 0 && (
            <PersonalInfo
              activeIndex={activeIndex}
              setActiveIndex={setActiveIndex}
            />
          )}

          {activeIndex === 1 && (
            <SelectPlans
              activeIndex={activeIndex}
              setActiveIndex={setActiveIndex}
            />
          )}

          {activeIndex === 2 && (
            <AddOns activeIndex={activeIndex} setActiveIndex={setActiveIndex} />
          )}

          {activeIndex === 3 && (
            <Summary
              activeIndex={activeIndex}
              setActiveIndex={setActiveIndex}
            />
          )}
        </div>
      </section>
    </>
  );
}
